exrsite/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path("", views.home, name="home"),
    path("about-us/", views.about, name="about"),
    path("services/", views.service, name="services"),
    path("services/car-insurance", views.car_insurance, name="car_insurance"),
    path("services/life-insurance", views.life_insurance, name="life_insurance"),
    path("services/health-insurance", views.health_insurance, name="health_insurance"),
    path("services/home-insurance", views.home_insurance, name="home_insurance"),
]

exrsite/exrsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exrsite/core/models.py
from django.db import models

# Create your models here.

exrsite/core/views.py
from django.shortcuts import render
from django.http import request


# Home view.
def home(request):
    return render(request, 'home.html')


# about view
def about(request):
    return render(request, 'about.html')


# service view
def service(request):
    return render(request, 'service.html')


# service view
def car_insurance(request):
    return render(request, 'car_insurance.html')


# service view
def life_insurance(request):
    return render(request, 'life_insurance.html')


# service view
def health_insurance(request):
    return render(request, 'health_insurance.html')


# service view
def home_insurance(request):
    return render(request, 'home_insurance.html')

exrsite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Insure - Insurance HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %} " rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Poppins:wght@600;700&display=swap" rel="stylesheet"/>

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet"/>

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet" />
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  </head>

  <body>
    <!-- Spinner Start -->
    <div
      id="spinner"
      class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
      <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->

    <!-- Topbar Start -->
    <div class="container-fluid bg-dark text-white-50 py-2 px-0 d-none d-lg-block">
      <div class="row gx-0 align-items-center">
        <div class="col-lg-7 px-5 text-start">
          <div class="h-100 d-inline-flex align-items-center me-4">
            <small class="fa fa-phone-alt me-2"></small>
            <small>+228 99416645</small>
          </div>
          <div class="h-100 d-inline-flex align-items-center me-4">
            <small class="far fa-envelope-open me-2"></small>
            <small>info@example.com</small>
          </div>
          <div class="h-100 d-inline-flex align-items-center me-4">
            <small class="far fa-clock me-2"></small>
            <small>Mon - Fri : 09 AM - 09 PM</small>
          </div>
        </div>
        <div class="col-lg-5 px-5 text-end">
          <div class="h-100 d-inline-flex align-items-center">
            <a class="text-white-50 ms-4" href=""><i class="fab fa-facebook-f"></i></a>
            <a class="text-white-50 ms-4" href=""><i class="fab fa-twitter"></i></a>
            <a class="text-white-50 ms-4" href=""><i class="fab fa-linkedin-in"></i></a>
            <a class="text-white-50 ms-4" href=""><i class="fab fa-instagram"></i></a>
          </div>
        </div>
      </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5">
      <a href="index.html" class="navbar-brand d-flex align-items-center">
        <h1 class="m-0">
          <img class="img-fluid me-3" src="{% static 'img/icon/icon-02-primary.png' %}" alt=""/>Excelsior
        </h1>
      </a>
      <button
        type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav mx-auto bg-light rounded pe-4 py-3 py-lg-0">
          <a href="{% url 'core:home' %}" class="nav-item nav-link active">Acceuil</a>
          <a href="{% url 'core:about' %}" class="nav-item nav-link">A Propos</a>
          <a href="{% url 'core:services' %}" class="nav-item nav-link">Nos Services</a>
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Assurances</a>
            <div class="dropdown-menu bg-light border-0 m-0">
              <a href="feature.html" class="dropdown-item">Features</a>
              <a href="appointment.html" class="dropdown-item">Appointment</a>
              <a href="team.html" class="dropdown-item">Team Members</a>
              <a href="testimonial.html" class="dropdown-item">Testimonial</a>
              <a href="404.html" class="dropdown-item">404 Page</a>
            </div>
          </div>
          <a href="contact.html" class="nav-item nav-link">Contactez-nous</a>
        </div>
      </div>
      <a href="" class="btn btn-primary px-3 d-none d-lg-block">Obtenir Une Cotation</a>
    </nav>
    <!-- Navbar End -->

    {% block content %}

    {% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">
      <div class="container py-5">
        <div class="row g-5">
          <div class="col-lg-3 col-md-6">
            <h1 class="text-white mb-4">
              <img
                class="img-fluid me-3" src="{% static 'img/icon/icon-02-light.png' %}" alt=""/>Excelsior
            </h1>
            <p>
              Nous sommes engagés à protéger votre avenir. Votre confiance, notre priorité.
            </p>
            <div class="d-flex pt-2">
              <a class="btn btn-square me-1" href=""><i class="fab fa-twitter"></i></a>
              <a class="btn btn-square me-1" href=""><i class="fab fa-facebook-f"></i></a>
              <a class="btn btn-square me-1" href=""><i class="fab fa-youtube"></i></a>
              <a class="btn btn-square me-0" href=""><i class="fab fa-linkedin-in"></i></a>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <h5 class="text-light mb-4">Adresse</h5>
            <p>
              <i class="fa fa-map-marker-alt me-3"></i>Adidogomé, Lomé, Togo
            </p>
            <p><i class="fa fa-phone-alt me-3"></i>+228 99416645</p>
            <p><i class="fa fa-envelope me-3"></i>agenceexcelsior@gmail.com</p>
          </div>
          <div class="col-lg-3 col-md-6">
            <h5 class="text-light mb-4">Quick Links</h5>
            <a class="btn btn-link" href="">About Us</a>
            <a class="btn btn-link" href="">Contact Us</a>
            <a class="btn btn-link" href="">Our Services</a>
            <a class="btn btn-link" href="">Terms & Condition</a>
            <a class="btn btn-link" href="">Support</a>
          </div>
          <div class="col-lg-3 col-md-6">
            <h5 class="text-light mb-4">Newsletter</h5>
            <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
            <div class="position-relative mx-auto" style="max-width: 400px">
              <input
                class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email"/>
              <button
                type="button" class="btn btn-secondary py-2 position-absolute top-0 end-0 mt-2 me-2"> SignUp
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="container-fluid copyright">
        <div class="container">
          <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
              &copy; <a href="#">Your Site Name</a>, All Right Reserved.
            </div>
            <div class="col-md-6 text-center text-md-end">
              <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
              Designed By <a href="https://htmlcodex.com">HTML Codex</a>
              <br />Distributed By:
              <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

exrsite/templates/car_insurance.html
<p>
    Votre véhicule est une extension de votre vie quotidienne, et notre assurance automobile est là pour vous
    offrir une protection fiable sur la route. Des accidents aux dommages en passant par le vol, nous avons conçu
    des solutions d'assurance complètes pour répondre à vos préoccupations spécifiques. Explorez nos différents
    plans d'assurance automobile, chacun adapté à votre style de vie et à vos besoins. Découvrez comment nous
    pouvons vous aider à rester serein au volant. Pour en savoir plus sur nos offres et personnaliser
    votre couverture, consultez notre gamme complète de solutions d'assurance automobile.
</p>

exrsite/templates/health_insurance.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <img src="{% static 'img/health.png' %}" alt="" class="img-fluid">
            </div>
            <div class="col-lg-6 ">
                <p class="lead" style="text-align: justify !important;">
                    Votre santé est une priorité, et notre assurance santé est conçue pour vous offrir
                    une couverture complète. Des consultations médicales aux frais d'hospitalisation, nous
                    nous engageons à vous fournir une protection fiable pour répondre à vos besoins de santé uniques.
                    Avec des plans flexibles et des avantages adaptés, nous vous accompagnons dans chaque étape de votre
                    parcours de soins.
                </p>
                <p class="lead" style="text-align: justify !important;">
                Explorez nos solutions d'assurance santé pour comprendre comment nous pouvons
                    contribuer à votre bien-être et à celui de votre famille. Pour en savoir plus sur nos offres et personnaliser
                    votre couverture, découvrez l'ensemble de nos solutions d'assurance santé.
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

exrsite/templates/home_insurance.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p>
    Votre maison est bien plus qu'un simple lieu de vie, c'est un sanctuaire. Notre assurance habitation
    personnalisée vous offre une protection complète pour votre espace précieux. Que ce soit contre les dommages
    structurels, le vol ou d'autres incidents imprévus, nous sommes là pour préserver votre tranquillité d'esprit.
    Explorez nos différentes options d'assurance habitation, conçues pour répondre à vos besoins spécifiques.
    Découvrez comment nous pouvons vous aider à protéger votre chez-vous et ce qui compte le plus pour vous.
    Pour en savoir plus sur nos offres et personnaliser votre couverture,
    consultez notre gamme complète de solutions d'assurance habitation.
</p>
{% endblock %}

exrsite/templates/insurance_wealth.html
<h1>Comment l'Assurance Crée de la Richesse pour Tous</h1>
<ul>
    <li>
        <h3>Votre Protection Financière Personnalisée</h3>
        <p>
            L'assurance offre une protection financière personnalisée contre les aléas de la vie tels que les accidents,
            les maladies graves et les catastrophes naturelles.
            Cela permet aux individus de préserver leur patrimoine en évitant des pertes financières inattendues.
        </p>
    </li>
    <li>
        <h3>Stabilité Économique Pour Vous et Votre Entreprise</h3>
        <p>
            En permettant aux entreprises de se protéger contre les risques financiers majeurs, l'assurance favorise la
            stabilité économique. Cette stabilité encourage l'investissement, stimule l'entrepreneuriat et contribue à
            la croissance économique en créant un environnement propice au développement des affaires.
        </p>
    </li>
    <li>
        <h3>Vos Primes, un Investissement dans Votre Avenir</h3>
        <p>
               Les primes versées par les assurés constituent une source de financement importante pour les compagnies d'assurance.
            Ces fonds sont ensuite investis dans des actifs productifs tels que des actions et des obligations, générant
            ainsi des rendements qui contribuent à la création de richesse.
        </p>
    </li>
    <li>
        <h3>  Soyez Acteur du Développement Économique </h3>
        <p>
           En permettant aux individus et aux entreprises de prendre des risques calculés, l'assurance joue un rôle
            clé dans le développement économique. Elle offre une bouée de sauvetage financière, encourageant ainsi
            l'innovation, l'expansion des entreprises et la création d'emplois.
        </p>
    </li>
    <li>
        <h3> Votre Résilience Financière, Notre Priorité </h3>
        <p>
               L'assurance joue un rôle essentiel dans la construction d'une société financièrement résiliente.
            En fournissant une sécurité financière, elle aide les individus et les entreprises à surmonter les obstacles
            financiers, favorisant ainsi une communauté plus robuste et capable de prospérer.
        </p>
    </li>
</ul>

exrsite/templates/life_insurance.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-xxl py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <img src="{% static 'img/life.png' %}" alt="" class="img-fluid">
            </div>
            <div class="col-lg-6 ">
                <p class="lead" style="text-align: justify !important;">
                    Parce que la vie est imprévisible, notre assurance vie vous offre la tranquillité d'esprit
                    en assurant une protection financière pour vos proches en cas de besoin. Avec des options
                    flexibles et adaptées à vos besoins spécifiques, nous sommes là pour vous accompagner tout au
                    long de votre parcours. Découvrez comment notre assurance vie peut être un pilier essentiel dans
                    la construction d'un avenir financier solide.
                </p>
                <p class="lead" style="text-align: justify !important;">
                Pour en savoir plus sur nos offres et
                personnaliser votre couverture, explorez notre gamme complète de solutions d'assurance vie.
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

exrsite/templates/service.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Service Start -->
    <div class="container-xxl py-5">
      <div class="container">
        <div class="text-center mx-auto" style="max-width: 500px">
          <h1 class="display-6 mb-5">
            Rien que pour vous, une large gamme de produits
          </h1>
        </div>
        <div class="row g-4 justify-content-center">
          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="service-item rounded h-100 p-5">
              <div class="d-flex align-items-center ms-n5 mb-4">
                <div
                  class="service-icon flex-shrink-0 bg-primary rounded-end me-4">
                  <img
                    class="img-fluid"
                    src="{% static 'img/icon/icon-10-light.png' %}" alt=""/>
                </div>
                <h4 class="mb-0">Assurance Vie</h4>
              </div>
              <p class="mb-4">
                Assurez votre avenir et celui de vos proches avec notre assurance vie sur mesure...
              </p>
              <a class="btn btn-light px-3" href="{% url 'core:life_insurance' %}">Plus</a>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
            <div class="service-item rounded h-100 p-5">
              <div class="d-flex align-items-center ms-n5 mb-4">
                <div
                  class="service-icon flex-shrink-0 bg-primary rounded-end me-4">
                  <img class="img-fluid"
                    src="{% static 'img/icon/icon-01-light.png' %}" alt=""/>
                </div>
                <h4 class="mb-0">Assurance Santé</h4>
              </div>
              <p class="mb-4">
                Priorisez votre bien-être avec notre assurance santé complète et personnalisée...
              </p>
              <a class="btn btn-light px-3" href="{% url 'core:health_insurance' %}">Plus</a>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
            <div class="service-item rounded h-100 p-5">
              <div class="d-flex align-items-center ms-n5 mb-4">
                <div
                  class="service-icon flex-shrink-0 bg-primary rounded-end me-4">
                  <img class="img-fluid"
                    src="{% static 'img/icon/icon-05-light.png' %}" alt=""/>
                </div>
                <h4 class="mb-0">Assurance Habitation</h4>
              </div>
              <p class="mb-4">
                Sécurisez votre chez-vous avec notre assurance habitation sur mesure...
              </p>
              <a class="btn btn-light px-3" href="{% url 'core:home_insurance' %}">Plus</a>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="service-item rounded h-100 p-5">
              <div class="d-flex align-items-center ms-n5 mb-4">
                <div
                  class="service-icon flex-shrink-0 bg-primary rounded-end me-4">
                  <img class="img-fluid"
                    src="{% static 'img/icon/icon-08-light.png' %}" alt=""/>
                </div>
                <h4 class="mb-0">Assurance Automobiles</h4>
              </div>
              <p class="mb-4">
                Roulez en toute sérénité avec notre assurance automobile adaptée à vos besoins...
              </p>
              <a class="btn btn-light px-3" href="{% url 'core:car_insurance' %}">Plus</a>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
            <div class="service-item rounded h-100 p-5">
              <div class="d-flex align-items-center ms-n5 mb-4">
                <div
                  class="service-icon flex-shrink-0 bg-primary rounded-end me-4">
                  <img class="img-fluid"
                    src="{% static 'img/icon/icon-07-light.png' %}" alt=""/>
                </div>
                <h4 class="mb-0">Assurance Entreprise</h4>
              </div>
              <p class="mb-4">
                Aliqu diam amet eos erat ipsum et lorem et sit, sed stet lorem
                sit clita duo justo erat amet
              </p>
              <a class="btn btn-light px-3" href="">Plus...</a>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
            <div class="service-item rounded h-100 p-5">
              <div class="d-flex align-items-center ms-n5 mb-4">
                <div
                  class="service-icon flex-shrink-0 bg-primary rounded-end me-4">
                  <img class="img-fluid"
                    src="{% static 'img/icon/icon-06-light.png' %}" alt=""/>
                </div>
                <h4 class="mb-0">Assurance des Biens</h4>
              </div>
              <p class="mb-4">
                Aliqu diam amet eos erat ipsum et lorem et sit, sed stet lorem
                sit clita duo justo erat amet
              </p>
              <a class="btn btn-light px-3" href="">Plus</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Service End -->
{% endblock %}